version: '2'
services:
    kucun-app:
        image: kucun
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kucun-mysql:3306/kucun?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kucun-mysql:
        extends:
            file: mysql.yml
            service: kucun-mysql
